version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=koala
      - POSTGRESQL_PASSWORD=koala
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - './.docker_data/postgresql:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=koala
      - KEYCLOAK_ADMIN_PASSWORD=koala
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_USER=koala
      - KEYCLOAK_DATABASE_PASSWORD=koala
      - KEYCLOAK_DATABASE_NAME=keycloak
    depends_on:
      - postgresql
